# This is a basic workflow to help you get started with Actions

name: update-database

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 12 * * 1-5'
    - cron:  '30 */1 * * 6'
    - cron:  '30 */1 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-database:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl https://www.fhnijlen.be/wedstrijden/jorik-doet-poging-hopelijk-lukt-het
